states_prompt = "the us states listed in alphabetical order"
states_list = [
    "alabama",
    "alaska",
    "arizona",
    "arkansas",
    "california",
    "colorado",
    "connecticut",
    "delaware",
    "florida",
    "georgia",
    "hawaii",
    "idaho",
    "illinois",
    "indiana",
    "iowa",
    "kansas",
    "kentucky",
    "louisiana",
    "maine",
    "maryland",
    "massachusetts",
    "michigan",
    "minnesota",
    "mississippi",
    "missouri",
    "montana",
    "nebraska",
    "nevada",
    "new hampshire",
    "new jersey",
    "new mexico",
    "new york",
    "north carolina",
    "north dakota",
    "ohio",
    "oklahoma",
    "oregon",
    "pennsylvania",
    "rhode island",
    "south carolina",
    "south dakota",
    "tennessee",
    "texas",
    "utah",
    "vermont",
    "virginia",
    "washington",
    "west virginia",
    "wisconsin",
    "wyoming",
]

planets_prompt = (
    "names of the planets from closest to the sun to furthest, including pluto"
)
planets_list = [
    "mercury",
    "venus",
    "earth",
    "mars",
    "jupiter",
    "saturn",
    "uranus",
    "neptune",
    "pluto",
]

elements_prompt = "the elements in the periodic table ending w/ calcium"
elements_list = [
    "hydrogen",
    "helium",
    "lithium",
    "beryllium",
    "boron",
    "carbon",
    "nitrogen",
    "oxygen",
    "fluorine",
    "neon",
    "sodium",
    "magnesium",
    "aluminum",
    "silicon",
    "phosphorus",
    "sulfur",
    "chlorine",
    "argon",
    "potassium",
    "calcium",
]

presidents_prompt = "the names of the first ten us presidents in chronological order"
presidents_list = [
    "george washington",
    "john adams",
    "thomas jefferson",
    "james madison",
    "james monroe",
    "john quincy adams",
    "andrew jackson",
    "martin van buren",
    "william henry harrison",
    "john tyler",
]

set_prompts = [states_prompt, planets_prompt, elements_prompt, presidents_prompt]
set_values = [states_list, planets_list, elements_list, presidents_list]
